"""add progress message tracking to query_batches

Revision ID: 306f8c36fe38
Revises: a65361fddfb0
Create Date: 2026-07-22 16:32:12.075533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306f8c36fe38'
down_revision: Union[str, None] = 'a65361fddfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_batches', sa.Column('progress_chat_id', sa.BigInteger(), nullable=True))
    op.add_column('query_batches', sa.Column('progress_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_batches', 'progress_message_id')
    op.drop_column('query_batches', 'progress_chat_id')
    # ### end Alembic commands ###
