"""remove codigos_nao_encontrados

Revision ID: 3a90a4d537b5
Revises: e1a1d883e4e1
Create Date: 2026-07-23 17:05:48.079879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a90a4d537b5'
down_revision: Union[str, None] = 'e1a1d883e4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_codigos_nao_encontrados_code_type', table_name='codigos_nao_encontrados')
    op.drop_table('codigos_nao_encontrados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_nao_encontrados',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('query_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='codigos_nao_encontrados_pkey'),
    sa.UniqueConstraint('code', 'query_type', name='uq_codigo_nao_encontrado', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_codigos_nao_encontrados_code_type', 'codigos_nao_encontrados', ['code', 'query_type'], unique=False)
    # ### end Alembic commands ###
