"""add codigos_nao_cadastrados

Revision ID: 6c46682ae3d9
Revises: 3a90a4d537b5
Create Date: 2026-07-23 17:23:16.806848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c46682ae3d9'
down_revision: Union[str, None] = '3a90a4d537b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_nao_cadastrados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('query_type', sa.String(length=20), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('vezes_confirmado', sa.Integer(), nullable=False),
    sa.Column('primeira_vez', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_vez', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'query_type', name='uq_codigo_nao_cadastrado')
    )
    op.create_index('ix_codigos_nao_cadastrados_code_type', 'codigos_nao_cadastrados', ['code', 'query_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_codigos_nao_cadastrados_code_type', table_name='codigos_nao_cadastrados')
    op.drop_table('codigos_nao_cadastrados')
    # ### end Alembic commands ###
