"""add codigos_nao_encontrados

Revision ID: e1a1d883e4e1
Revises: 306f8c36fe38
Create Date: 2026-07-23 08:32:12.663663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a1d883e4e1'
down_revision: Union[str, None] = '306f8c36fe38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_nao_encontrados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('query_type', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'query_type', name='uq_codigo_nao_encontrado')
    )
    op.create_index('ix_codigos_nao_encontrados_code_type', 'codigos_nao_encontrados', ['code', 'query_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_codigos_nao_encontrados_code_type', table_name='codigos_nao_encontrados')
    op.drop_table('codigos_nao_encontrados')
    # ### end Alembic commands ###
